#!/bin/bash

make_ifts()
{
  tput smcup
  set -x
  clear
  DIRECTORY=$(cd `dirname $0` && pwd)
  itsname=libeft-its
  eftname=eft-menu
  cat $( echo -e $DIRECTORY/eft-its/*.its )  >  $DIRECTORY/$itsname
  echo -e "\neft-its library created $DIRECTORY/$libname\n\n"
  echo -e "\nTest $eftname $itsname Funtions"
  echo -e "\n\tPress any key to test...\n"
  read -n 1
( bash $DIRECTORY/$eftname ) 
  tput rmcup  

}

make_ifts